# SPDX-FileCopyrightText: 2026 Thomas Ascher <thomas.ascher@gmx.at>
#
# SPDX-License-Identifier: MIT
"""The application task: a specification, and what is graded against it."""
from pathlib import Path

SPEC = '''# Todo Application

A Python package that keeps a list of tasks, serves it over HTTP as JSON, and
renders it as a web page. This file is the contract; it is graded against, so
build to it exactly. Do not edit this file.

## Layout

    pyproject.toml            packaging metadata
    src/todoapp/__init__.py   exports create_app()
    src/todoapp/__main__.py   `python -m todoapp` starts the server
    tests/test_app.py         your tests, covering each endpoint
    (further modules under src/todoapp/ as you see fit)

`pyproject.toml` declares a name, a version, Flask as a dependency, a build
backend, and a console entry point under `[project.scripts]`.

## Runtime

  * `create_app()` returns a configured Flask application.
  * `python -m todoapp` serves on 127.0.0.1, on the port named by the `PORT`
    environment variable, defaulting to 5000.
  * State lives on disk at the path named by the `TODO_DB` environment variable,
    defaulting to `tasks.db` beside the working directory, and survives a
    restart of the process.
  * When that store is empty, three example tasks are created in it.

Flask, pytest and requests are installed already. Do not install anything and do
not create a virtual environment -- that includes this package: run and test it
from the source tree, which is how it will be run when it is checked.

    PYTHONPATH=src python -m todoapp
    PYTHONPATH=src python -m pytest tests

## The task object

    {"id": 3, "title": "Buy milk", "description": "Semi-skimmed",
     "color": "#3366cc", "done": false, "position": 2}

`color` is a CSS hex colour of the form `#rrggbb`. `position` orders the list,
and every listing is sorted by it ascending.

## HTTP API

    GET    /api/tasks              200, the tasks as a JSON array
           ?done=true              only the checked ones
           ?done=false             only the open ones
           ?q=TEXT                 only those whose title or description
                                   contains TEXT, ignoring case
    POST   /api/tasks              body {title, description, color}
                                   201, the created task, open, placed last
    GET    /api/tasks/<id>         200, the task; 404 if there is no such id
    PATCH  /api/tasks/<id>         body: any subset of title, description,
                                   color, done. Fields not named are left
                                   alone. 200, the updated task
    DELETE /api/tasks/<id>         204
    POST   /api/tasks/reorder      body {"order": [id, id, ...]}
                                   200, the tasks in that new order, which
                                   later listings keep
    GET    /                       the HTML page

## The page

Fetches the current tasks from the API when it loads, and renders each one in
order: its title, its description if it has one, its colour, and whether it
is checked off -- in a form a reader can actually see. Embedding the data in
the page without displaying it does not satisfy this. It offers a field for
adding a task, and an existing task's title, description or colour can be
edited from the page too, saved through the update endpoint. A task can be
dragged to a new place in the list, which is saved through the reorder
endpoint. Nothing about the visual style beyond that is prescribed: a
checkbox or a click can both mark a task done, and any layout that shows the
required information is acceptable.
'''


TASK = dict(
    id="ag_todoapp",
    prompt="Read SPEC.md and build what it describes: a complete, installable Python "
           "package with the HTTP API, the storage, the web page and your own tests. "
           "Work through it end to end, run the application and your tests with "
           "`{py}` to confirm it behaves as the specification says, and fix what does "
           "not. Do not edit SPEC.md.",
    files={"SPEC.md": SPEC},
    immutable=["SPEC.md"],
    # Scored per requirement rather than pass or fail: packaging, an eleven-route
    # API, a store that survives a restart, a page and tests are too much surface
    # for one verdict, which would say only that something was missing.
    #
    # The score is nonetheless coarser than eighteen checks suggest, because
    # thirteen of them cannot be attempted unless the application starts. That is
    # why this is its own tool rather than part of the screen: a model that
    # mis-named one file scores what a model that wrote nothing scores, and a
    # measurement that blunt should not be grading anyone.
    graded=True,
    verify_src_path=str(Path(__file__).parent / "checks" / "todo_app_check.py"),
    verify_timeout=900,
    # Slow local models write this for a long time, and cutting one off midway
    # measures the clock rather than the model.
    min_timeout=3600,
    # The point of the exercise is as much the application as the score, so it is
    # created where it can be found and opened afterwards.
    retain=True,
)
